name: Build and Push Trade Producer Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for mvnw
        run: chmod +x ./tradeproducer/mvnw
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --severity-threshold=high --file=tradeproducer/pom.xml -d
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./tradeproducer

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t tradeproducer:latest ./tradeproducer

      - name: Push Docker Image
        run: docker push tradeproducer:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
