name: Build and Push Docker Images for Tradeproducer and Tradeconsumer modules

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for mvnw
        run: chmod +x ./tradeproducer/mvnw ./tradeconsumer/mvnw

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities in tradeproducer
        run: snyk test --severity-threshold=high --file=tradeproducer/pom.xml -d
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities in tradeconsumer
        run: snyk test --severity-threshold=high --file=tradeconsumer/pom.xml -d
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build tradeproducer with Maven
        run: mvn clean install
        working-directory: ./tradeproducer

      - name: Build tradeconsumer with Maven
        run: mvn clean install
        working-directory: ./tradeconsumer

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build tradeproducer Docker Image
        run: docker build -t tradeproducer:latest ./tradeproducer

      - name: Build tradeconsumer Docker Image
        run: docker build -t tradeconsumer:latest ./tradeconsumer

      - name: Push tradeproducer Docker Image
        run: |
          docker tag tradeproducer:latest ${{ secrets.DOCKERHUB_USERNAME }}/tradeproducer:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tradeproducer:latest

      - name: Push tradeconsumer Docker Image
        run: |
          docker tag tradeconsumer:latest ${{ secrets.DOCKERHUB_USERNAME }}/tradeconsumer:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tradeconsumer:latest
